### ISSUE TITLE
Using a broken version

### ISSUE THREAD

**Issue by God-damnit-all** [zmwangx/chocolatey-googler#2]
Google has recently changed things and broke googler, so googler had to update with some changes to fix them. If you could, please update the chocolatey package, thanks.

**Comment by zmwangx** [comment]
Oh yeah, I forgot about choco, will do. However, just a heads up, I’ve been experiencing wait times of > a week in the moderator queue lately, so it won’t be approved soon.

**Comment by zmwangx** [comment]
Sorry I never remembered to address this.

I've set an automated GitHub Action to submit new versions in the future (runs daily). https://github.com/zmwangx/chocolatey-googler/runs/712022571
